"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2q=+ob^0m*vo2x5joyk9k9$a0$q+1@mc@^t6tgi-7*8j2wk0fg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'backup',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Backup storage settings
BACKUP_ROOT = BASE_DIR / 'backup_data'

# Secrets file for OAuth tokens (stored outside database)
# File will be created with chmod 600 permissions
# For extra security, place on an encrypted volume
SECRETS_FILE = Path(os.environ.get('SECRETS_FILE', BASE_DIR / '.secrets.json'))

# Google OAuth settings
# Try to load from secrets file first, fall back to environment variables
def _get_google_oauth_config():
    """Load Google OAuth config from secrets file or environment."""
    # Import here to avoid circular dependency
    from backup.secrets import get_oauth_client_config

    # Try secrets file first
    config = get_oauth_client_config('google')
    if config:
        return (
            config.get('client_id', ''),
            config.get('client_secret', ''),
            config.get('redirect_uri', 'http://localhost:8000/oauth/google/callback')
        )

    # Fall back to environment variables (for backwards compatibility)
    return (
        os.environ.get('GOOGLE_CLIENT_ID', ''),
        os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        os.environ.get('GOOGLE_REDIRECT_URI', 'http://localhost:8000/oauth/google/callback')
    )

GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI = _get_google_oauth_config()

# Sync engine configuration
SYNC_BATCH_SIZE = 100  # Number of changes to process per batch
SYNC_MISSING_THRESHOLD = 2  # Number of syncs before quarantine
SYNC_DOWNLOAD_TIMEOUT = 300  # Download timeout in seconds

# Garbage collection settings
GC_BATCH_SIZE = 100  # Number of items to process per batch
GC_DEFAULT_KEEP_DAYS = 30  # Days to keep versions and quarantined items
GC_DEFAULT_KEEP_VERSIONS = 10  # Minimum number of versions to keep per file

# Celery configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat schedule
from datetime import timedelta
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'sync-all-accounts': {
        'task': 'backup.tasks.sync_all_accounts',
        'schedule': timedelta(hours=6),
    },
    'run-garbage-collection': {
        'task': 'backup.tasks.run_gc_task',
        'schedule': crontab(hour=3, minute=0),  # 3 AM daily
    },
}
