# Generated by Django 6.0 on 2026-01-05 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('onedrive', 'OneDrive')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('provider', 'email')},
            },
        ),
        migrations.CreateModel(
            name='BackupBlob',
            fields=[
                ('digest', models.CharField(max_length=71, primary_key=True, serialize=False)),
                ('size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blobs', to='backup.account')),
            ],
        ),
        migrations.CreateModel(
            name='BackupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_item_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('item_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('provider_modified_at', models.DateTimeField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('active', 'Active'), ('deleted_upstream', 'Deleted Upstream'), ('missing_upstream', 'Missing Upstream'), ('quarantined', 'Quarantined'), ('purged', 'Purged')], default='active', max_length=20)),
                ('state_changed_at', models.DateTimeField(auto_now_add=True)),
                ('missing_since_sync_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backup.backupitem')),
            ],
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_path', models.TextField()),
                ('etag_or_revision', models.CharField(blank=True, max_length=255)),
                ('content_modified_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('update', 'Update'), ('pre_delete', 'Pre-Delete'), ('manual_snapshot', 'Manual Snapshot'), ('conflict', 'Conflict'), ('restore_point', 'Restore Point')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='backup.account')),
                ('backup_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='backup.backupitem')),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='backup.backupblob')),
            ],
        ),
        migrations.CreateModel(
            name='SyncRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_root_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sync_cursor', models.TextField(blank=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_roots', to='backup.account')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keep_last_n', models.PositiveIntegerField(default=10)),
                ('keep_days', models.PositiveIntegerField(default=30)),
                ('max_storage_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='backup.account')),
                ('sync_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='backup.syncroot')),
            ],
            options={
                'verbose_name_plural': 'Retention policies',
            },
        ),
        migrations.AddField(
            model_name='backupitem',
            name='sync_root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backup.syncroot'),
        ),
        migrations.AddIndex(
            model_name='backupblob',
            index=models.Index(fields=['account', 'created_at'], name='backup_back_account_f3442e_idx'),
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['backup_item', 'captured_at'], name='backup_file_backup__2bc831_idx'),
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['account', 'captured_at'], name='backup_file_account_4ce2eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncroot',
            unique_together={('account', 'provider_root_id')},
        ),
        migrations.AddIndex(
            model_name='backupitem',
            index=models.Index(fields=['state'], name='backup_back_state_1e7481_idx'),
        ),
        migrations.AddIndex(
            model_name='backupitem',
            index=models.Index(fields=['provider_item_id'], name='backup_back_provide_fde759_idx'),
        ),
        migrations.AddIndex(
            model_name='backupitem',
            index=models.Index(fields=['sync_root', 'state'], name='backup_back_sync_ro_d51d8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backupitem',
            unique_together={('sync_root', 'provider_item_id')},
        ),
    ]
