# Generated by Django 6.0 on 2026-01-06 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='token_expires_at',
        ),
    ]
