# Generated by Django 6.0 on 2026-01-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_remove_token_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('start_cursor', models.TextField(blank=True)),
                ('end_cursor', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('files_added', models.PositiveIntegerField(default=0)),
                ('files_updated', models.PositiveIntegerField(default=0)),
                ('files_deleted', models.PositiveIntegerField(default=0)),
                ('files_quarantined', models.PositiveIntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('sync_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='backup.syncroot')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('file_added', 'File Added'), ('file_updated', 'File Updated'), ('file_deleted', 'File Deleted'), ('file_quarantined', 'File Quarantined'), ('error', 'Error'), ('checkpoint', 'Checkpoint')], max_length=20)),
                ('provider_file_id', models.CharField(blank=True, max_length=255)),
                ('file_path', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('backup_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_events', to='backup.backupitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backup.syncsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='syncsession',
            index=models.Index(fields=['sync_root', '-started_at'], name='backup_sync_sync_ro_b73e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='syncsession',
            index=models.Index(fields=['status'], name='backup_sync_status_3ebfba_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['session', 'timestamp'], name='backup_sync_session_cb01f7_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['event_type'], name='backup_sync_event_t_05d2f0_idx'),
        ),
    ]
