# Generated by Django 6.0 on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_syncsession_syncevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(
                default=360,
                help_text='Minutes between syncs. 0 = use global schedule only.'
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='next_sync_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Next scheduled sync time.'
            ),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(
                fields=['is_active', 'next_sync_at'],
                name='backup_acco_is_acti_c6e8a7_idx'
            ),
        ),
    ]
